"""Add global_settings table for branding

Revision ID: 1d9370a370a8
Revises: 568643dc4bc2
Create Date: 2025-11-24 11:25:46.848867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d9370a370a8'
down_revision: Union[str, Sequence[str], None] = '568643dc4bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_settings',
    sa.Column('logo_url', sa.String(), nullable=True, comment='URL to custom logo (stored in MinIO). Falls back to default if null.'),
    sa.Column('accent_color', sa.String(length=7), nullable=False, comment='Primary accent color in hex format (e.g., #0ea5e9 for sky-blue)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # Insert default settings row (singleton with id=1)
    from uuid import uuid4
    from datetime import datetime
    op.execute(
        f"""
        INSERT INTO global_settings (id, logo_url, accent_color, created_at, updated_at)
        VALUES (
            '{uuid4()}',
            NULL,
            '#0ea5e9',
            '{datetime.utcnow().isoformat()}',
            '{datetime.utcnow().isoformat()}'
        )
        """
    )

    op.drop_column('section_migrations', 'schema_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section_migrations', sa.Column('schema_hash', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_table('global_settings')
    # ### end Alembic commands ###
