"""Remove published from NodeSetupVersion

Revision ID: 553f94d1fde7
Revises: e2d7aa8467d9
Create Date: 2025-07-21 08:48:35.450874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '553f94d1fde7'
down_revision: Union[str, Sequence[str], None] = 'e2d7aa8467d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node_setup_versions', 'published')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node_setup_versions', sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
