"""empty message

Revision ID: 7fd3e97bc14e
Revises: 553f94d1fde7
Create Date: 2025-08-02 10:47:17.864864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fd3e97bc14e'
down_revision: Union[str, Sequence[str], None] = '553f94d1fde7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('require_api_key', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'require_api_key')
    # ### end Alembic commands ###
