"""empty message

Revision ID: 8400a7869f40
Revises: 7fd3e97bc14e
Create Date: 2025-08-04 11:10:10.880182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8400a7869f40'
down_revision: Union[str, Sequence[str], None] = '7fd3e97bc14e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_stage_name'), 'stages', type_='unique')
    op.create_unique_constraint('uq_stage_name_per_project', 'stages', ['name', 'project_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_stage_name_per_project', 'stages', type_='unique')
    op.create_unique_constraint(op.f('uq_stage_name'), 'stages', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
