"""add_chat_window_access_table_and_remove_chat_window_fields

Revision ID: 982a0dfcb6ad
Revises: e8c3d4ef7c08
Create Date: 2025-10-03 10:00:20.013082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '982a0dfcb6ad'
down_revision: Union[str, Sequence[str], None] = 'e8c3d4ef7c08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_window_access',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('chat_window_id', sa.UUID(), nullable=False),
    sa.Column('can_view_flow', sa.Boolean(), nullable=False),
    sa.Column('can_edit_flow', sa.Boolean(), nullable=False),
    sa.Column('can_view_output', sa.Boolean(), nullable=False),
    sa.Column('show_response_transparency', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_window_id'], ['chat_windows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'chat_window_id', name='uix_account_chat_window')
    )
    op.drop_column('chat_windows', 'user_ids')
    op.drop_column('chat_windows', 'view_mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_windows', sa.Column('view_mode', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('chat_windows', sa.Column('user_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_table('chat_window_access')
    # ### end Alembic commands ###
