"""Add unique constraint for section handle per project

Revision ID: d75d7affcece
Revises: 98373d07cd26
Create Date: 2025-10-31 13:48:17.609515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd75d7affcece'
down_revision: Union[str, Sequence[str], None] = '98373d07cd26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_section_handle_per_project', 'sections', ['project_id', 'handle'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_section_handle_per_project', 'sections', type_='unique')
    # ### end Alembic commands ###
