"""project change

Revision ID: 7c6a95f51392
Revises: 17de80197077
Create Date: 2025-07-09 11:09:25.351832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c6a95f51392'
down_revision: Union[str, Sequence[str], None] = '17de80197077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blueprints', 'deleted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blueprints', sa.Column('deleted_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
