"""project change

Revision ID: f62728c95675
Revises: 9be199bc6094
Create Date: 2025-07-10 14:34:40.313646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f62728c95675'
down_revision: Union[str, Sequence[str], None] = '9be199bc6094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_secrets', sa.Column('stage', sa.String(), nullable=False))
    op.add_column('project_secrets', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('project_secrets', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_secrets', 'updated_at')
    op.drop_column('project_secrets', 'created_at')
    op.drop_column('project_secrets', 'stage')
    # ### end Alembic commands ###
